### PR TITLE
:rocket: Release libhal as version 1.0.0

### LINKED ISSUE #477: Interface APIs all return structures
Prepare the interfaces for API compatibility in the future by making every return value for each interface function return a structure. For things that current return `status` we would return `return<some_struct_t>` with a name that makes sense. So that in the future, if we need to add more return information to the API we can without breaking the API. The ABI breaks but we don't intend on supporting a consistent ABI.

For example:

```C++
class adc
{
public:
  [[nodiscard]] result<float> read() noexcept
  {
    return driver_read();
  }

private:
  virtual result<float> driver_read() noexcept = 0;
};
```

should become 

```C++
class adc
{
public:
  struct read_t { float value; };

  [[nodiscard]] result<read_t> read() noexcept
  {
    return driver_read();
  }

private:
  virtual result<read_t> driver_read() noexcept = 0;
};
```

This way, if we discover in the future that we absolutely need to return the bit resolution of the ADC through this return value channel, we can do so without breaking anything. We can give the value a default "unset" value or use `std::optional<>` in that case which default initializes to `std::nullopt`.

### LINKED ISSUE #652: Make all interrupts return void
Setting up an interrupt should be an infallible process in general and should not return a result. To return a result would mean that the caller had some way to handle the event not going through, which should not be possible for interrupts. Interrupts are deeply connected to their target device and for them to fail would mean that there is a typo or a bug in the program, which is something that we do not try to support error handling for.

### PR DESCRIPTION
**Pull request by kammce**
:boom: Release libhal as version 1.0.0

libhal is a dependency for the SJSU Robotics team and thus its SemVer
number must be set to 1.0.0. This is important because it will help with
communicating to our users when APIs break, when features are added
and when patches are added. This isn't possible with versions below
1.0.0 as stated in SemVer.

The following changes were made to improve flexibility, improve
extensibility and remove some technical debt.

- :zap: Add input clamp for `hal::dac` write operation
- :zap: Add input clamp for `hal::motor` power operation
- :memo: Update documentation for each interface and each interface
  building block
- :boom: All non configuration and non interrupt APIs return structures

Resolves #477
Resolves #652

### CODE REVIEW

File: include/libhal/can.hpp [hunk 1]
```diff
@@ -96,22 +143,54 @@ class can
...
     return driver_configure(p_settings);
   }
+
   /**
-   * @brief Send a message
+   * @brief Transition the CAN device from "bus-off" to "bus-on"
    *
-   * @param p_message - the message to be sent
+   * WARNING: Calling this function when the device is already in "bus-on" will
+   * have no affect. This function is not necessary to call after creating the
```
Comment (MaliaLabor) [inline include/libhal/can.hpp]: I think this needs to be "effect" not "affect"

File: include/libhal/interrupt_pin.hpp [hunk 2]
```diff
@@ -16,42 +17,64 @@ namespace hal {
...
-    /// HIGH voltage.
+    /**
+     * @brief Trigger and interrupt when a pin transitions from LOW voltage to
+     * HIGH voltage.
+     *
+     */
     rising = 1,
-    /// Trigger and interrupt when a pin transitions it state
+    /**
+     * @brief Trigger and interrupt when a pin transitions it state
```
Comment (MaliaLabor) [inline include/libhal/interrupt_pin.hpp]: change to "its"

File: include/libhal/magnetometer.hpp [hunk 3]
```diff
@@ -17,16 +17,31 @@ namespace hal {
...
+     * @brief Magnetic field strength in the X axis, relative to the device's
+     * reference frame.
+     *
+     */
     gauss x;
-    /// Magnetic field strength in the X axis, relative to the device's
-    /// reference frame.
+
+    /**
+     * @brief Magnetic field strength in the X axis, relative to the device's
```
Comment (MaliaLabor) [inline include/libhal/magnetometer.hpp]: "Y axis"

File: include/libhal/magnetometer.hpp [hunk 4]
```diff
@@ -17,16 +17,31 @@ namespace hal {
...
+     * reference frame.
+     *
+     */
     gauss y;
-    /// Magnetic field strength in the X axis, relative to the device's
-    /// reference frame.
+
+    /**
+     * @brief Magnetic field strength in the X axis, relative to the device's
```
Comment (MaliaLabor) [inline include/libhal/magnetometer.hpp]: "Z axis"
